# config.py - Configuration for Philippine regions and provinces

# All possible variations of region identifiers
REGION_IDENTIFIERS = [
    # Region I - Ilocos
    "REGION I", "REGION 1", "I", "ILOCOS REGION", "ILOCOS", "REGION I (ILOCOS REGION)",
    
    # Region II - Cagayan Valley
    "REGION II", "REGION 2", "II", "CAGAYAN VALLEY", "REGION II (CAGAYAN VALLEY)",
    
    # Region III - Central Luzon
    "REGION III", "REGION 3", "III", "CENTRAL LUZON", "REGION III (CENTRAL LUZON)",
    
    # Region IV-A - CALABARZON
    "REGION IV-A", "REGION IVA", "REGION 4-A", "REGION 4A", "IV-A", "IVA", "CALABARZON", "REGION IV-A (CALABARZON)",
    
    # Region IV-B - MIMAROPA
    "REGION IV-B", "REGION IVB", "REGION 4-B", "REGION 4B", "IV-B", "IVB", "MIMAROPA", "MIMAROPA REGION",
    
    # Region V - Bicol
    "REGION V", "REGION 5", "V", "BICOL REGION", "BICOL", "REGION V (BICOL REGION)",
    
    # Region VI - Western Visayas
    "REGION VI", "REGION 6", "VI", "WESTERN VISAYAS", "REGION VI (WESTERN VISAYAS)",
    
    # Region VII - Central Visayas
    "REGION VII", "REGION 7", "VII", "CENTRAL VISAYAS", "REGION VII (CENTRAL VISAYAS)",
    
    # Region VIII - Eastern Visayas
    "REGION VIII", "REGION 8", "VIII", "EASTERN VISAYAS", "REGION VIII (EASTERN VISAYAS)",
    
    # Region IX - Zamboanga Peninsula
    "REGION IX", "REGION 9", "IX", "ZAMBOANGA PENINSULA", "ZAMBOANGA", "REGION IX (ZAMBOANGA PENINSULA)",
    
    # Region X - Northern Mindanao
    "REGION X", "REGION 10", "X", "NORTHERN MINDANAO", "REGION X (NORTHERN MINDANAO)",
    
    # Region XI - Davao
    "REGION XI", "REGION 11", "XI", "DAVAO REGION", "DAVAO", "REGION XI (DAVAO REGION)",
    
    # Region XII - SOCCSKSARGEN
    "REGION XII", "REGION 12", "XII", "SOCCSKSARGEN", "REGION XII (SOCCSKSARGEN)",
    
    # Region XIII - Caraga
    "REGION XIII", "REGION 13", "XIII", "CARAGA", "REGION XIII (Caraga)",
    
    # NCR
    "NCR", "NATIONAL CAPITAL REGION", "METRO MANILA", "NATIONAL CAPITAL REGION (NCR)",
    
    # CAR
    "CAR", "CORDILLERA ADMINISTRATIVE REGION", "CORDILLERA", "CORDILLERA ADMINISTRATIVE REGION (CAR)",
    
    # BARMM
    "BARMM", "ARMM", "BANGSAMORO", "BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)", "BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO",
    
    # NIR
    "NIR", "NEGROS ISLAND REGION",
]

REGION_PROVINCE_MAP = {
    # Region I - Ilocos
    "ILOCOS REGION": ["ILOCOS NORTE", "ILOCOS SUR", "LA UNION", "PANGASINAN", "DAGUPAN"],
    "ILOCOS": ["ILOCOS NORTE", "ILOCOS SUR", "LA UNION", "PANGASINAN", "DAGUPAN"],
    "REGION I": ["ILOCOS NORTE", "ILOCOS SUR", "LA UNION", "PANGASINAN", "DAGUPAN"],
    "REGION 1": ["ILOCOS NORTE", "ILOCOS SUR", "LA UNION", "PANGASINAN", "DAGUPAN"],
    "I": ["ILOCOS NORTE", "ILOCOS SUR", "LA UNION", "PANGASINAN", "DAGUPAN"],
    "REGION I (ILOCOS REGION)": ["ILOCOS NORTE", "ILOCOS SUR", "LA UNION", "PANGASINAN", "DAGUPAN"],
    
    # Region II - Cagayan Valley
    "CAGAYAN VALLEY": ["BATANES", "CAGAYAN", "ISABELA", "NUEVA VIZCAYA", "QUIRINO"],
    "REGION II": ["BATANES", "CAGAYAN", "ISABELA", "NUEVA VIZCAYA", "QUIRINO"],
    "REGION 2": ["BATANES", "CAGAYAN", "ISABELA", "NUEVA VIZCAYA", "QUIRINO"],
    "II": ["BATANES", "CAGAYAN", "ISABELA", "NUEVA VIZCAYA", "QUIRINO"],
    "REGION II (CAGAYAN VALLEY)": ["BATANES", "CAGAYAN", "ISABELA", "NUEVA VIZCAYA", "QUIRINO"],
    
    # Region III - Central Luzon
    "CENTRAL LUZON": ["AURORA", "BATAAN", "BULACAN", "NUEVA ECIJA", "PAMPANGA", "TARLAC", "ZAMBALES", "ANGELES CITY", "OLONGAPO CITY"],
    "REGION III": ["AURORA", "BATAAN", "BULACAN", "NUEVA ECIJA", "PAMPANGA", "TARLAC", "ZAMBALES", "ANGELES CITY", "OLONGAPO CITY"],
    "REGION 3": ["AURORA", "BATAAN", "BULACAN", "NUEVA ECIJA", "PAMPANGA", "TARLAC", "ZAMBALES", "ANGELES CITY", "OLONGAPO CITY"],
    "III": ["AURORA", "BATAAN", "BULACAN", "NUEVA ECIJA", "PAMPANGA", "TARLAC", "ZAMBALES", "ANGELES CITY", "OLONGAPO CITY"],
    "REGION III (CENTRAL LUZON)": ["AURORA", "BATAAN", "BULACAN", "NUEVA ECIJA", "PAMPANGA", "TARLAC", "ZAMBALES", "ANGELES CITY", "OLONGAPO CITY"],
    
    # Region IV-A - CALABARZON
    "CALABARZON": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    "REGION IV-A": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    "REGION IVA": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    "REGION 4-A": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    "REGION 4A": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    "IV-A": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    "IVA": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    "REGION IV-A (CALABARZON)": ["BATANGAS", "CAVITE", "LAGUNA", "QUEZON", "RIZAL"],
    
    # Region IV-B - MIMAROPA
    "MIMAROPA": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    "REGION IV-B": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    "REGION IVB": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    "REGION 4-B": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    "REGION 4B": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    "IV-B": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    "IVB": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    "MIMAROPA REGION": ["MARINDUQUE", "OCCIDENTAL MINDORO", "ORIENTAL MINDORO", "PALAWAN", "ROMBLON", "PUERTO PRINCESA"],
    
    # Region V - Bicol
    "BICOL REGION": ["ALBAY", "CAMARINES NORTE", "CAMARINES SUR", "CATANDUANES", "MASBATE", "SORSOGON", "NAGA CITY"],
    "BICOL": ["ALBAY", "CAMARINES NORTE", "CAMARINES SUR", "CATANDUANES", "MASBATE", "SORSOGON", "NAGA CITY"],
    "REGION V": ["ALBAY", "CAMARINES NORTE", "CAMARINES SUR", "CATANDUANES", "MASBATE", "SORSOGON", "NAGA CITY"],
    "REGION 5": ["ALBAY", "CAMARINES NORTE", "CAMARINES SUR", "CATANDUANES", "MASBATE", "SORSOGON", "NAGA CITY"],
    "V": ["ALBAY", "CAMARINES NORTE", "CAMARINES SUR", "CATANDUANES", "MASBATE", "SORSOGON", "NAGA CITY"],
    "REGION V (BICOL REGION)": ["ALBAY", "CAMARINES NORTE", "CAMARINES SUR", "CATANDUANES", "MASBATE", "SORSOGON", "NAGA CITY"],
    
    # Region VI - Western Visayas
    "WESTERN VISAYAS": ["AKLAN", "ANTIQUE", "CAPIZ", "GUIMARAS", "ILOILO", "NEGROS OCCIDENTAL", "ILOILO CITY", "BACOLOD CITY"],
    "REGION VI": ["AKLAN", "ANTIQUE", "CAPIZ", "GUIMARAS", "ILOILO", "NEGROS OCCIDENTAL", "ILOILO CITY", "BACOLOD CITY"],
    "REGION 6": ["AKLAN", "ANTIQUE", "CAPIZ", "GUIMARAS", "ILOILO", "NEGROS OCCIDENTAL", "ILOILO CITY", "BACOLOD CITY"],
    "VI": ["AKLAN", "ANTIQUE", "CAPIZ", "GUIMARAS", "ILOILO", "NEGROS OCCIDENTAL", "ILOILO CITY", "BACOLOD CITY"],
    "REGION VI (WESTERN VISAYAS)": ["AKLAN", "ANTIQUE", "CAPIZ", "GUIMARAS", "ILOILO", "NEGROS OCCIDENTAL", "ILOILO CITY", "BACOLOD CITY"],
    
    # Region VII - Central Visayas
    "CENTRAL VISAYAS": ["BOHOL", "CEBU", "NEGROS ORIENTAL", "SIQUIJOR", "CEBU CITY", "LAPU-LAPU CITY", "MANDAUE CITY"],
    "REGION VII": ["BOHOL", "CEBU", "NEGROS ORIENTAL", "SIQUIJOR", "CEBU CITY", "LAPU-LAPU CITY", "MANDAUE CITY"],
    "REGION 7": ["BOHOL", "CEBU", "NEGROS ORIENTAL", "SIQUIJOR", "CEBU CITY", "LAPU-LAPU CITY", "MANDAUE CITY"],
    "VII": ["BOHOL", "CEBU", "NEGROS ORIENTAL", "SIQUIJOR", "CEBU CITY", "LAPU-LAPU CITY", "MANDAUE CITY"],
    "REGION VII (CENTRAL VISAYAS)": ["BOHOL", "CEBU", "NEGROS ORIENTAL", "SIQUIJOR", "CEBU CITY", "LAPU-LAPU CITY", "MANDAUE CITY"],
    
    # Region VIII - Eastern Visayas
    "EASTERN VISAYAS": ["BILIRAN", "EASTERN SAMAR", "LEYTE", "NORTHERN SAMAR", "SAMAR", "SAMAR (WESTERN SAMAR)", "SOUTHERN LEYTE", "TACLOBAN CITY"],
    "REGION VIII": ["BILIRAN", "EASTERN SAMAR", "LEYTE", "NORTHERN SAMAR", "SAMAR", "SAMAR (WESTERN SAMAR)", "SOUTHERN LEYTE", "TACLOBAN CITY"],
    "REGION 8": ["BILIRAN", "EASTERN SAMAR", "LEYTE", "NORTHERN SAMAR", "SAMAR", "SAMAR (WESTERN SAMAR)", "SOUTHERN LEYTE", "TACLOBAN CITY"],
    "VIII": ["BILIRAN", "EASTERN SAMAR", "LEYTE", "NORTHERN SAMAR", "SAMAR", "SAMAR (WESTERN SAMAR)", "SOUTHERN LEYTE", "TACLOBAN CITY"],
    "REGION VIII (EASTERN VISAYAS)": ["BILIRAN", "EASTERN SAMAR", "LEYTE", "NORTHERN SAMAR", "SAMAR", "SAMAR (WESTERN SAMAR)", "SOUTHERN LEYTE", "TACLOBAN CITY"],
    
    # Region IX - Zamboanga Peninsula
    "ZAMBOANGA PENINSULA": ["ZAMBOANGA DEL NORTE", "ZAMBOANGA DEL SUR", "ZAMBOANGA SIBUGAY", "ZAMBOANGA CITY", "SULU", "CITY OF ISABELA (Not a Province)"],
    "ZAMBOANGA": ["ZAMBOANGA DEL NORTE", "ZAMBOANGA DEL SUR", "ZAMBOANGA SIBUGAY", "ZAMBOANGA CITY", "SULU", "CITY OF ISABELA (Not a Province)"],
    "REGION IX": ["ZAMBOANGA DEL NORTE", "ZAMBOANGA DEL SUR", "ZAMBOANGA SIBUGAY", "ZAMBOANGA CITY", "SULU", "CITY OF ISABELA (Not a Province)"],
    "REGION 9": ["ZAMBOANGA DEL NORTE", "ZAMBOANGA DEL SUR", "ZAMBOANGA SIBUGAY", "ZAMBOANGA CITY", "SULU", "CITY OF ISABELA (Not a Province)"],
    "IX": ["ZAMBOANGA DEL NORTE", "ZAMBOANGA DEL SUR", "ZAMBOANGA SIBUGAY", "ZAMBOANGA CITY", "SULU", "CITY OF ISABELA (Not a Province)"],
    "REGION IX (ZAMBOANGA PENINSULA)": ["ZAMBOANGA DEL NORTE", "ZAMBOANGA DEL SUR", "ZAMBOANGA SIBUGAY", "ZAMBOANGA CITY", "SULU", "CITY OF ISABELA (Not a Province)"],
    
    # Region X - Northern Mindanao
    "NORTHERN MINDANAO": ["BUKIDNON", "CAMIGUIN", "LANAO DEL NORTE", "MISAMIS OCCIDENTAL", "MISAMIS ORIENTAL", "CAGAYAN DE ORO CITY", "ILIGAN CITY"],
    "REGION X": ["BUKIDNON", "CAMIGUIN", "LANAO DEL NORTE", "MISAMIS OCCIDENTAL", "MISAMIS ORIENTAL", "CAGAYAN DE ORO CITY", "ILIGAN CITY"],
    "REGION 10": ["BUKIDNON", "CAMIGUIN", "LANAO DEL NORTE", "MISAMIS OCCIDENTAL", "MISAMIS ORIENTAL", "CAGAYAN DE ORO CITY", "ILIGAN CITY"],
    "X": ["BUKIDNON", "CAMIGUIN", "LANAO DEL NORTE", "MISAMIS OCCIDENTAL", "MISAMIS ORIENTAL", "CAGAYAN DE ORO CITY", "ILIGAN CITY"],
    "REGION X (NORTHERN MINDANAO)": ["BUKIDNON", "CAMIGUIN", "LANAO DEL NORTE", "MISAMIS OCCIDENTAL", "MISAMIS ORIENTAL", "CAGAYAN DE ORO CITY", "ILIGAN CITY"],
    
    # Region XI - Davao
    "DAVAO REGION": ["DAVAO DE ORO", "DAVAO DE ORO (COMPOSTELA VALLEY)", "DAVAO DEL NORTE", "DAVAO DEL SUR", "DAVAO OCCIDENTAL", "DAVAO ORIENTAL", "DAVAO CITY"],
    "DAVAO": ["DAVAO DE ORO", "DAVAO DE ORO (COMPOSTELA VALLEY)", "DAVAO DEL NORTE", "DAVAO DEL SUR", "DAVAO OCCIDENTAL", "DAVAO ORIENTAL", "DAVAO CITY"],
    "REGION XI": ["DAVAO DE ORO", "DAVAO DE ORO (COMPOSTELA VALLEY)", "DAVAO DEL NORTE", "DAVAO DEL SUR", "DAVAO OCCIDENTAL", "DAVAO ORIENTAL", "DAVAO CITY"],
    "REGION 11": ["DAVAO DE ORO", "DAVAO DE ORO (COMPOSTELA VALLEY)", "DAVAO DEL NORTE", "DAVAO DEL SUR", "DAVAO OCCIDENTAL", "DAVAO ORIENTAL", "DAVAO CITY"],
    "XI": ["DAVAO DE ORO", "DAVAO DE ORO (COMPOSTELA VALLEY)", "DAVAO DEL NORTE", "DAVAO DEL SUR", "DAVAO OCCIDENTAL", "DAVAO ORIENTAL", "DAVAO CITY"],
    "REGION XI (DAVAO REGION)": ["DAVAO DE ORO", "DAVAO DE ORO (COMPOSTELA VALLEY)", "DAVAO DEL NORTE", "DAVAO DEL SUR", "DAVAO OCCIDENTAL", "DAVAO ORIENTAL", "DAVAO CITY"],
    
    # Region XII - SOCCSKSARGEN
    "SOCCSKSARGEN": ["COTABATO CITY", "COTABATO (NORTH COTABATO)", "SARANGANI", "SOUTH COTABATO", "SULTAN KUDARAT", "GENERAL SANTOS CITY", "MAGUINDANAO DEL NORTE"],
    "REGION XII": ["COTABATO CITY", "COTABATO (NORTH COTABATO)", "SARANGANI", "SOUTH COTABATO", "SULTAN KUDARAT", "GENERAL SANTOS CITY", "MAGUINDANAO DEL NORTE"],
    "REGION 12": ["COTABATO CITY", "COTABATO (NORTH COTABATO)", "SARANGANI", "SOUTH COTABATO", "SULTAN KUDARAT", "GENERAL SANTOS CITY", "MAGUINDANAO DEL NORTE"],
    "XII": ["COTABATO CITY", "COTABATO (NORTH COTABATO)", "SARANGANI", "SOUTH COTABATO", "SULTAN KUDARAT", "GENERAL SANTOS CITY", "MAGUINDANAO DEL NORTE"],
    "REGION XII (SOCCSKSARGEN)": ["COTABATO CITY", "COTABATO (NORTH COTABATO)", "SARANGANI", "SOUTH COTABATO", "SULTAN KUDARAT", "GENERAL SANTOS CITY", "MAGUINDANAO DEL NORTE"],
    
    # Region XIII - Caraga
    "CARAGA": ["AGUSAN DEL NORTE", "Agusan Del Norte", "AGUSAN DEL SUR", "BUTUAN CITY", "DINAGAT ISLANDS", "SURIGAO DEL NORTE", "SURIGAO DEL SUR"],
    "REGION XIII": ["AGUSAN DEL NORTE", "Agusan Del Norte", "AGUSAN DEL SUR", "BUTUAN CITY", "DINAGAT ISLANDS", "SURIGAO DEL NORTE", "SURIGAO DEL SUR"],
    "REGION 13": ["AGUSAN DEL NORTE", "Agusan Del Norte", "AGUSAN DEL SUR", "BUTUAN CITY", "DINAGAT ISLANDS", "SURIGAO DEL NORTE", "SURIGAO DEL SUR"],
    "XIII": ["AGUSAN DEL NORTE", "Agusan Del Norte", "AGUSAN DEL SUR", "BUTUAN CITY", "DINAGAT ISLANDS", "SURIGAO DEL NORTE", "SURIGAO DEL SUR"],
    "REGION XIII (Caraga)": ["AGUSAN DEL NORTE", "Agusan Del Norte", "AGUSAN DEL SUR", "BUTUAN CITY", "DINAGAT ISLANDS", "SURIGAO DEL NORTE", "SURIGAO DEL SUR"],
   
    # NCR
    #"NCR": ["NCR, City of Manila, First District (Not a Province)", "NCR, Second District (Not a Province)", "NCR, Third District (Not a Province)", "NCR, Fourth District (Not a Province)"],
    #"NATIONAL CAPITAL REGION": ["NCR, City of Manila, First District (Not a Province)", "NCR, Second District (Not a Province)", "NCR, Third District (Not a Province)", "NCR, Fourth District (Not a Province)"],
    #"METRO MANILA": ["NCR, City of Manila, First District (Not a Province)", "NCR, Second District (Not a Province)", "NCR, Third District (Not a Province)", "NCR, Fourth District (Not a Province)"],
    #"NATIONAL CAPITAL REGION (NCR)": ["NCR, City of Manila, First District (Not a Province)", "NCR, Second District (Not a Province)", "NCR, Third District (Not a Province)", "NCR, Fourth District (Not a Province)"],
    
    # CAR
    "CAR": ["ABRA", "APAYAO", "BENGUET", "IFUGAO", "KALINGA", "MOUNTAIN PROVINCE"],
    "CORDILLERA ADMINISTRATIVE REGION": ["ABRA", "APAYAO", "BENGUET", "IFUGAO", "KALINGA", "MOUNTAIN PROVINCE"],
    "CORDILLERA": ["ABRA", "APAYAO", "BENGUET", "IFUGAO", "KALINGA", "MOUNTAIN PROVINCE"],
    "CORDILLERA ADMINISTRATIVE REGION (CAR)": ["ABRA", "APAYAO", "BENGUET", "IFUGAO", "KALINGA", "MOUNTAIN PROVINCE"],
    
    # BARMM
    "BARMM": ["BASILAN", "COTABATO CITY", "INTERIM PROVINCE", "LANAO DEL SUR", "MAGUINDANAO", "MAGUINDANAO DEL NORTE", "MAGUINDANAO DEL SUR", "SULU", "TAWI-TAWI"],
    "ARMM": ["BASILAN", "COTABATO CITY", "INTERIM PROVINCE", "LANAO DEL SUR", "MAGUINDANAO", "MAGUINDANAO DEL NORTE", "MAGUINDANAO DEL SUR", "SULU", "TAWI-TAWI"],
    "BANGSAMORO": ["BASILAN", "COTABATO CITY", "INTERIM PROVINCE", "LANAO DEL SUR", "MAGUINDANAO", "MAGUINDANAO DEL NORTE", "MAGUINDANAO DEL SUR", "SULU", "TAWI-TAWI"],
    "BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)": ["BASILAN", "COTABATO CITY", "INTERIM PROVINCE", "LANAO DEL SUR", "MAGUINDANAO", "MAGUINDANAO DEL NORTE", "MAGUINDANAO DEL SUR", "SULU", "TAWI-TAWI"],
    "BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO": ["BASILAN", "COTABATO CITY", "INTERIM PROVINCE", "LANAO DEL SUR", "MAGUINDANAO", "MAGUINDANAO DEL NORTE", "MAGUINDANAO DEL SUR", "SULU", "TAWI-TAWI"],
    
    # NIR - Negros Island Region
    "NIR": ["NEGROS OCCIDENTAL", "NEGROS ORIENTAL", "SIQUIJOR", "BACOLOD CITY"],
    "NEGROS ISLAND REGION": ["NEGROS OCCIDENTAL", "NEGROS ORIENTAL", "SIQUIJOR", "BACOLOD CITY"],
}

# Highly Urbanized Cities mapped to their regions
# These cities are independent from provinces and act as both province and municipality level
HUCS = {
    # NCR cities
    'CALOOCAN': 'NCR',
    'LAS PIÑAS': 'NCR',
    'MAKATI': 'NCR',
    'MALABON': 'NCR',
    'MANDALUYONG': 'NCR',
    'MANILA': 'NCR',
    'MARIKINA': 'NCR',
    'MUNTINLUPA': 'NCR',
    'NAVOTAS': 'NCR',
    'PARAÑAQUE': 'NCR',
    'PASAY': 'NCR',
    'PASIG': 'NCR',
    'QUEZON CITY': 'NCR',
    'SAN JUAN': 'NCR',
    'TAGUIG': 'NCR',
    'VALENZUELA': 'NCR',
    
    # Other HUCs
    'ANGELES': 'REGION 3',
    'BACOLOD': 'REGION 6',
    'BAGUIO': 'CAR',
    'BUTUAN': 'CARAGA',
    'CAGAYAN DE ORO': 'REGION 10',
    'CEBU CITY': 'REGION 7',
    'DAVAO CITY': 'REGION 11',
    'GENERAL SANTOS': 'REGION 12',
    'ILIGAN': 'REGION 10',
    'ILOILO CITY': 'REGION 6',
    'LAPU-LAPU': 'REGION 7',
    'LUCENA': 'CALABARZON',
    'MANDAUE': 'REGION 7',
    'OLONGAPO': 'REGION 3',
    'PUERTO PRINCESA': 'MIMAROPA',
    'TACLOBAN': 'REGION 8',
    'ZAMBOANGA CITY': 'REGION 9',

    # Independent Component Cities (ICCs) - also need special handling
    'DAGUPAN': 'REGION 1',
    'NAGA': 'REGION 5',
    'ORMOC': 'REGION 8',
    'SANTIAGO': 'REGION 2',
    'SANTIAGO CITY': 'REGION 2',
    'COTABATO CITY': 'BARMM',
}

